apiVersion: v1
kind: Config
clusters:
- name: "production"
  cluster:
    server: "https://10.10.1.1/k8s/clusters/c-ckk6z"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2akNDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GMyTmprMwpNemt4T0RBZUZ3MHlOVEV5TWprd01UQTFNVGhhRncwek5URXlNamN3TVRBMU1UaGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56WTJPVGN6T1RFNE1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRUpmdTNTM2VMTTdERQpTanhMaHZqRWdxRUJ6d2FKTGtIR2F5cDRoT\
      0RsTHR6WktDNTlVMWF6NHdyWWhvK0RaZUMvRUdFUWYyZm1IQTFDClVlNThBTnFITnFOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGU\
      Hp6UE5MWk5pa3pRdlFsU2J6eFc4Vm5YSzRwTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDKwpYR\
      lpqYVpXMjk5eCtFQ2VlVlVJUThkODhlZVBSenRnSzZVdGRYdytVQkFJaEFJVlJLUzBoRTBhUDlvd\
      nlWOThICktSczNFUEM5b251RWZCZjUrdUsvMCtrMgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "production"
  user:
    token: "kubeconfig-user-dwk5k86jb9:rmz6jn7f9wfp4srjmxgbltzndtvd9x5pdj6x56rprg67ddb6nsdsn4"


contexts:
- name: "production"
  context:
    user: "production"
    cluster: "production"

current-context: "production"
